version: '3.9'
services:
  cuttlefish-backend:
    build: .
    container_name: cuttlefish_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
